server {
    listen 80;
    server_name cronograma.nexaflow-ia.com;

    root /var/www/cronograma.nexaflow-ia.com/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }
}
